---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: reusablepipeline_key
    region: us-east-1
    image: ami-0aeeebd8d2ab47354
    id: "web-app"
    sec_group: "{{ id }}-sec"
  tasks:
    - name: Provisioning EC2 instances
      block:
      - name: Create security group
        amazon.aws.ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          vpc_id: vpc-58d42b25
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
        register: result_sec_group
      - name: Provision instance(s)
        amazon.aws.ec2:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group: "{{ sec_group }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          vpc_subnet_id: subnet-8408a6a5
          wait: true
          count: 1
    - name: Download and deploy artifacts
      block:
      - name: Deploying artifacts
        ansible.builtin.copy:
           src: /var/lib/jenkins/workspace/generic_build/server/target/server.jar
           dest: /tmp/server.jar
